FOREACH (_INC_DIR   crt/include  sdk/include/ucrt  sdk/include/um  sdk/include/shared)
    SET(_AUX_COMPILE_FLAGS "${_AUX_COMPILE_FLAGS} /I${XWIN_PREFIX}/${_INC_DIR}")
ENDFOREACH ()

SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${_AUX_COMPILE_FLAGS}")
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${_AUX_COMPILE_FLAGS}")

SET(_AUX_LINK_FLAGS "")
FOREACH (_LIB_DIR   crt/lib/x86_64  sdk/lib/um/x86_64   sdk/lib/ucrt/x86_64)
    SET(_AUX_LINK_FLAGS "${_AUX_LINK_FLAGS} /libpath:${XWIN_PREFIX}/${_LIB_DIR}")
ENDFOREACH ()

SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${_AUX_LINK_FLAGS}")
SET(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${_AUX_LINK_FLAGS}")
SET(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} ${_AUX_LINK_FLAGS}")
